In [19]:
import numpy as np
import pandas as pd
df=pd.read_csv("D:/luminar/heart (1).csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak   
0     63    1   3       145   233  1.0        0      150      0      2.3  \
1     37    1   2       130   250  0.0        1      187      0      3.5   
2     41    0   1       130   204  0.0        0      172      0      1.4   
3     56    1   1       120   236  0.0        1      178      0      0.8   
4     57    0   0       120   354  0.0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241  0.0        1      123      1      0.2   
299   45    1   3       110   264  0.0        1      132      0      1.2   
300   68    1   0       144   193  1.0        1      141      0      3.4   
301   57    1   0       130   131  0.0        1      115      1      1.2   
302   57    0   1       130   236  0.0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0   1.0       1  
1        0   0   2.0       1  
2        2   0   2.0       1  
3        2   0   2.0       1  
4        2   0   2.0       1  
..     ...  ..   ...     ...  
298      1   0   3.0       0  
299      1   0   3.0       0  
300      1   2   3.0       0  
301      1   1   3.0       0  
302      1   1   2.0       0  

[303 rows x 14 columns]

In [20]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope   
0   63    1   3       145   233  1.0        0      150      0      2.3      0  \
1   37    1   2       130   250  0.0        1      187      0      3.5      0   
2   41    0   1       130   204  0.0        0      172      0      1.4      2   
3   56    1   1       120   236  0.0        1      178      0      0.8      2   
4   57    0   0       120   354  0.0        1      163      1      0.6      2   

   ca  thal  target  
0   0   1.0       1  
1   0   2.0       1  
2   0   2.0       1  
3   0   2.0       1  
4   0   2.0       1

In [21]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         5
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        6
target      0
dtype: int64

In [22]:
df.drop(['age'],axis=1,inplace=True)

In [23]:
x=df['fbs'].median()
y=df['thal'].median()

In [24]:
df['fbs'].fillna(x,inplace=True)
df['thal'].fillna(y,inplace=True)

In [25]:
df.isna().sum()

sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [26]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)

In [28]:
x_train

array([[  0.,   0., 180., ...,   2.,   0.,   2.],
       [  1.,   2., 150., ...,   2.,   0.,   3.],
       [  0.,   0., 130., ...,   1.,   0.,   3.],
       ...,
       [  1.,   1., 130., ...,   2.,   0.,   2.],
       [  1.,   2., 125., ...,   0.,   1.,   2.],
       [  1.,   0., 142., ...,   1.,   3.,   2.]])

In [29]:
from sklearn.preprocessing import StandardScaler
scn=StandardScaler()
scn.fit(x_train)
x_train=scn.transform(x_train)
x_test=scn.transform(x_test)

In [30]:
#model
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
knn=KNeighborsClassifier()
g=GaussianNB()
s=SVC()
lst=[knn,g,s]

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
for i in lst:
    print(i)
    i.fit(x_train,y_train)
    y_pred=i.predict(x_test)
    y_pred
    print(accuracy_score(y_test,y_pred))
    print(confusion_matrix(y_test,y_pred))
    print(classification_report(y_test,y_pred))

KNeighborsClassifier()
0.8021978021978022
[[30 14]
 [ 4 43]]
              precision    recall  f1-score   support

           0       0.88      0.68      0.77        44
           1       0.75      0.91      0.83        47

    accuracy                           0.80        91
   macro avg       0.82      0.80      0.80        91
weighted avg       0.82      0.80      0.80        91

GaussianNB()
0.8901098901098901
[[34 10]
 [ 0 47]]
              precision    recall  f1-score   support

           0       1.00      0.77      0.87        44
           1       0.82      1.00      0.90        47

    accuracy                           0.89        91
   macro avg       0.91      0.89      0.89        91
weighted avg       0.91      0.89      0.89        91

SVC()
0.8571428571428571
[[34 10]
 [ 3 44]]
              precision    recall  f1-score   support

           0       0.92      0.77      0.84        44
           1       0.81      0.94      0.87        47

    accuracy              